name: Release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always
  MOD_NAME: wheeler_rs

jobs:
  build_example:
    strategy:
      fail-fast: false
      matrix:
        job:
          # - { target: aarch64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
          # - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
    runs-on: ${{ matrix.job.os }}

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.8
        with:
          prefix-key: cargo-debug-${{ matrix.job.target }}

      - name: Build dll
        run: cargo xtask build --dest-mode root --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.MOD_NAME }}
          path: |
            ./build/mods/${{ env.MOD_NAME }}/
